---
name: bosh

releases:
- name: bosh
  url: http://bosh.io/d/github.com/cloudfoundry/bosh?v=166
  sha1: cc25ccbf8609a0fe56a7fe6ce0b0010286bcf6a1
- name: bosh-esxcloud-cpi
  version: latest
  url: file://bosh-esxcloud-cpi-0+dev.137.tgz

resource_pools:
- name: vms
  network: default
  stemcell:
    url: file://bosh-stemcell-0000-esxcloud-esxi-ubuntu-trusty-go_agent.tgz
  cloud_properties:
    vm_flavor: core-200
    disk_flavor: core-200

disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties:
    disk_flavor: core-200

networks:
- name: default
  type: manual
  subnets:
  - range: 10.146.38.0/23
    gateway: 10.146.39.253
    dns: [10.132.71.1]
    cloud_properties: {name: "VM VLAN"}

jobs:
- name: bosh
  instances: 1

  networks:
  - name: default
    static_ips: [10.146.38.111]

  templates:
  - name: nats
    release: bosh
  - name: redis
    release: bosh
  - name: blobstore
    release: bosh
  - name: postgres
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: powerdns
    release: bosh
  - name: cpi
    release: bosh-esxcloud-cpi

  resource_pool: vms
  persistent_disk_pool: disks

  properties:
    ntp: &ntp [10.132.71.1]

    nats:
      user: nats
      password: nats-password
      address: 127.0.0.1
      port: 4222

    blobstore:
      address: 10.146.38.111
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}
      options:
        endpoint: http://10.146.38.111:25250
        user: agent
        password: agent-password

    postgres: &db
      user: bosh
      password: bosh-password
      host: 127.0.0.1
      port: 5432
      database: bosh
      adapter: postgres

    redis:
      password: redis-password
      listen_addresss: 127.0.0.1
      address: 127.0.0.1

    director:
      name: bosh-in-esxcloud
      address: 127.0.0.1
      db: *db
      cpi_job: cpi

    hm:
      http: {user: hm, password: hm-password}
      director_account: {user: admin, password: admin}
      resurrector_enabled: true

    agent: {mbus: "nats://nats:nats-password@10.146.38.111:4222"}

    dns:
      address: 127.0.0.1
      db: *db

    # esxcloud job template
    esxcloud: &esxcloud
      target: http://10.146.38.100:8080
      user: dev
      password: pwd
      tenant: demo
      project: 0b7859ec-f708-41d6-bb41-f1ed34670231
      token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwaC1hZG1pbkBlc3hjbG91ZCIsImF1ZCI6WyJwaC1hZG1pbkBlc3hjbG91ZCIsInJzX2VzeGNsb3VkIl0sInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIGF0X2dyb3VwcyByc19lc3hjbG91ZCIsImlzcyI6Imh0dHBzOlwvXC8xMC4xNDYuMTcuMjFcL29wZW5pZGNvbm5lY3RcL2VzeGNsb3VkIiwiZ3JvdXBzIjpbImVzeGNsb3VkXFxzZzEiLCJlc3hjbG91ZFxcRXZlcnlvbmUiXSwidG9rZW5fY2xhc3MiOiJhY2Nlc3NfdG9rZW4iLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwiZXhwIjoxNDQ0NDgyNTA2LCJpYXQiOjE0NDQ0MTA1MDYsInRlbmFudCI6ImVzeGNsb3VkIiwianRpIjoiQmQ0NzRMVm4xS0VFVHJXQlBsVjViMFlWMUhsQ1ZzbFFjRU96U0VnS3A1SSJ9.kWDZqaeC3L1w77qwcqMrW3SFdaSisz_h9dDLkub_Pj0hSIZZNCepFjplB4YnDhTxtIgl-6Q-hTd5w9oL3qrG1lAN_pcnlKJU8uwsK0x85Lm8ta7-P1cZykIQYhAhPi7l_R9VFTvj8Vor3fZ7ZrVWYHeoyyiUUEQKfqzy_pEWodZWfZgCIktV21-0b-qxOKz9V0KEHJiqyYrqX7D02GeMBKxQXDYVV1CNUWtDpkEcGM7BIf1JOSoS19RVrlW-QQhvQBFsXxPJCwx4vn7IV99yPSzHvMhBz4mI1CylVxWtl9iu2Dc5qcCXG9Cuk5JutxqYvcmTQAbnhExeB-MhY7GbfOwsnz1qkXIxNPCjLhQrsbDGj7tUfDjsJ40A4lwYLSafYmMPKEunAgnshx7vhDYvsDUDCGmiHGdj08LOwV8rKVZq4D0Be5pvzZP3DQ5TroIePx9fYbE02Bdgzm5RFDBD-ZbFbQIYzgiLxhQyZSVWCaxcq77NshSJD4GfFMs7W_9Z389zLRgoTx8z0VpJ-HH_enUtn1GoFGdP8kuQGl2zImkhIvBTgjBYlcZu5f2fZL6V3tRHzCw9Ij1lIgYkFO0ii83U9imZ5cNMkOgQlwsBN6wNpWToB2XoN_hcXKzxHHUYwHBvbb2jE10WPZAH0ktPY8pjkV5snmmVT1fKTUR5CBM

cloud_provider:
  template: {name: cpi, release: bosh-esxcloud-cpi}
  mbus: "https://mbus:mbus-password@10.146.38.111:6868"

  properties:
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore:
      provider: local
      options:
        blobstore_path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp
    esxcloud: *esxcloud
