---
cpi_mkisofs/cdrtools-3.00.tar.bz2:
  object_id: 695d26fa-cce2-44d2-9855-4551b3e33bc0
  sha: 6464844d6b936d4f43ee98a04d637cd91131de4e
  size: 1978563
cpi_mkisofs/patch-include_schily_sha2.h:
  object_id: d7844983-f089-4b59-ad8b-7fe475f492af
  sha: 6c2c06b7546face6dd58c3fb39484b9120e3e1ca
  size: 648
cpi_mkisofs/smake-1.2.4.tar.bz2:
  object_id: 95662e0d-cb75-4ded-a5e0-4aba5067e3df
  sha: 677af2a1b768d5dfd3bd71dc46f81992e798191b
  size: 426050
golang_1.6/go1.6.linux-amd64.tar.gz:
  object_id: c6efe75b-9fe5-44a7-ae0b-2db46252b1de
  sha: !binary |-
    MDFhNmEyOGRiZTMxYTUzMTAzYjYwMDk3OWJiYmJkNjNhODEwNDQ1Ng==
  size: 84799480
